"""Rendering an :class:`EqPreset` into Equalizer APO's config syntax.

Pure functions over strings: no files, no install required, so the
format is testable to the last decimal. Given that the rest of this
integration can only be verified with APO actually installed, pushing as
much logic as possible into a pure function like this is a deliberate
tactic — it shrinks the untestable part to "did the bytes reach the
disk".

Syntax (from Equalizer APO's Configuration reference)::

    Preamp: -6.5 dB
    Filter: ON PK Fc 50.0 Hz Gain -10.0 dB Q 2.50
    Filter: ON LSC Fc 300 Hz Gain 5.0 dB Q 0.6473
    Filter: ON HSC Fc 100 Hz Gain -6.0 dB Q 0.4272
    Filter: ON LPQ Fc 10000 Hz Q 0.400
    Filter: ON HPQ Fc 20.0 Hz Q 0.500

Lines that don't parse are silently ignored, which is what makes ``#``
comments work — and also why a typo here would fail *quietly*, as bad
audio rather than an error. Hence the tests.

Why the Q-parameterised shelf types (``LSC``/``HSC``) rather than the
plain ``LS``/``HS``: our domain models every band with a Q, and the
Q-variants are the ones that take it. The plain variants use a
slope-based formulation with no Q at all, so a band's Q would be
silently dropped and the sound wouldn't match the curve on screen.
"""

from __future__ import annotations

from typing import assert_never

from trxmp.domain.equalizer import EqBand, EqPreset
from trxmp.dsp.biquad import FilterType

TRXMP_CONFIG_FILENAME = "trxmp.txt"

_HEADER = (
    "# Generated by Trxmp. Do not edit by hand.\n"
    "# This file is rewritten every time Trxmp applies a preset.\n"
)


def render_config(preset: EqPreset, sample_rate: float) -> str:
    """The full APO config text for ``preset``.

    The preamp written here is the *safe* preamp — the value the headroom
    analysis computed from the cascade's real peak response, not whatever
    the preset asked for. That's this project's clipping protection
    reaching all the way out to system-wide audio: boost four bands by
    9 dB and Trxmp quietly pulls the preamp down to match, so nothing
    clips on the way to the driver.
    """
    lines = [_HEADER, f"Preamp: {preset.safe_preamp_db(sample_rate):.2f} dB"]
    lines.extend(_render_filter(index, band) for index, band in enumerate(preset.bands, start=1))
    return "\n".join(lines) + "\n"


def render_bypass_config() -> str:
    """A config that does nothing, for when the EQ is switched off.

    Deliberately not an empty file: an explicit zero preamp with no
    filters documents *why* the file is empty, and leaves the plumbing
    (the Include line in config.txt) intact so switching back on is
    instant rather than a re-installation.
    """
    return (
        "# Generated by Trxmp. The equalizer is currently switched OFF.\n"
        "# Audio passes through untouched.\n"
        "Preamp: 0.00 dB\n"
    )


def _render_filter(index: int, band: EqBand) -> str:
    """One ``Filter`` line.

    The index is cosmetic — APO's reference says the number "is not
    interpreted and can be omitted" — but numbering the lines makes the
    file readable, and readable output is what lets a user debug their
    own system without us.
    """
    frequency = f"Fc {band.frequency_hz:.2f} Hz"
    gain = f"Gain {band.gain_db:.2f} dB"
    q = f"Q {band.q:.4f}"

    match band.filter_type:
        case FilterType.PEAKING:
            body = f"PK {frequency} {gain} {q}"
        case FilterType.LOW_SHELF:
            body = f"LSC {frequency} {gain} {q}"
        case FilterType.HIGH_SHELF:
            body = f"HSC {frequency} {gain} {q}"
        case FilterType.LOW_PASS:
            body = f"LPQ {frequency} {q}"  # pass filters take no gain
        case FilterType.HIGH_PASS:
            body = f"HPQ {frequency} {q}"
        case _ as unreachable:
            assert_never(unreachable)

    return f"Filter {index}: ON {body}"
